export enum Content {
  title = 'Video-App',
  loveIcon = '<3',
  deleteIcon = 'X',
  displays = 'Liczba wyświetleń:',
  likes = 'Liczba polubień:',
  showAllVideos = 'Wszystkie filmy',
  showFavoriteVideos = 'Ulubione',
  dateOfAddingVideo = 'Data dodania:',
  tooltipDeleteAll = 'Usuń wszystko',
  tooltipGridChange = 'Zmień widok',
  tooltipLoved = 'Pokaż ulubione',
  tooltipSort = 'Sortuj',
  questionDefault = 'Czy na pewno?',
  questionDeletAll = 'Czy na pewno chcesz usunąć wszystkie filmy?',
  addButton = 'Dodaj',
  inputLabel = 'Tutaj wklej link do filmu',
  close = 'Zamknij',
  yes = 'Tak',
  no = 'Nie',
}
