import { Videos } from './video.model';

export const DEMO_VIDEOS: Videos = [
  {
    platform: 'youtube',
    favorite: false,
    date: '2022-09-25T22:00:05.811Z',
    videoId: 'uITl2iRE2-g',
    title: 'Piękna historia pewnego fakapu',
    img: 'https://i.ytimg.com/vi/uITl2iRE2-g/mqdefault.jpg',
    viewCount: '204270',
    likes: '12164',
    playLink: 'http://www.youtube.com/embed/uITl2iRE2-g',
  },
  {
    platform: 'youtube',
    favorite: false,
    date: '2022-09-25T22:00:27.107Z',
    videoId: 'dkv1MoTy_d8',
    title: 'Karkonoska Ibiza - Z HRejterami Wśród Zwierząt',
    img: 'https://i.ytimg.com/vi/dkv1MoTy_d8/mqdefault.jpg',
    viewCount: '143808',
    likes: '6750',
    playLink: 'http://www.youtube.com/embed/dkv1MoTy_d8',
  },
  {
    platform: 'youtube',
    favorite: false,
    date: '2022-09-25T22:00:37.871Z',
    videoId: 'Nt0izk2wxxY',
    title: 'Dołącz do elitarnego grona słodzących herbatę - zgarnij 100k',
    img: 'https://i.ytimg.com/vi/Nt0izk2wxxY/mqdefault.jpg',
    viewCount: '154997',
    likes: '6026',
    playLink: 'http://www.youtube.com/embed/Nt0izk2wxxY',
  },
  {
    platform: 'youtube',
    favorite: false,
    date: '2022-09-25T22:00:48.226Z',
    videoId: 'MnjQV--o1-0',
    title: 'Gdy masz jedno hasło do wszystkiego',
    img: 'https://i.ytimg.com/vi/MnjQV--o1-0/mqdefault.jpg',
    viewCount: '395457',
    likes: '16283',
    playLink: 'http://www.youtube.com/embed/MnjQV--o1-0',
  },
  {
    platform: 'youtube',
    favorite: false,
    date: '2022-09-25T22:00:59.102Z',
    videoId: '6MjT53puqTc',
    title: 'Terapeuta ustawień systemowych',
    img: 'https://i.ytimg.com/vi/6MjT53puqTc/mqdefault.jpg',
    viewCount: '213997',
    likes: '7170',
    playLink: 'http://www.youtube.com/embed/6MjT53puqTc',
  },
  {
    platform: 'youtube',
    favorite: false,
    date: '2022-09-25T22:01:10.169Z',
    videoId: 'jy0yaeLodjU',
    title: 'Chciał moje klucze od mieszkania',
    img: 'https://i.ytimg.com/vi/jy0yaeLodjU/mqdefault.jpg',
    viewCount: '262046',
    likes: '14228',
    playLink: 'http://www.youtube.com/embed/jy0yaeLodjU',
  },
  {
    platform: 'youtube',
    favorite: false,
    date: '2022-09-25T22:01:21.089Z',
    videoId: 'Ci-Guiwy-5I',
    title: 'Z HRejterami wśród zwierząt - Bukowiec',
    img: 'https://i.ytimg.com/vi/Ci-Guiwy-5I/mqdefault.jpg',
    viewCount: '218374',
    likes: '9300',
    playLink: 'http://www.youtube.com/embed/Ci-Guiwy-5I',
  },
  {
    platform: 'youtube',
    favorite: false,
    date: '2022-09-25T22:01:34.181Z',
    videoId: 'l6qSgPOpJm4',
    title: 'Gdy twój znajomy znowu wymyśli aplikację za miliony',
    img: 'https://i.ytimg.com/vi/l6qSgPOpJm4/mqdefault.jpg',
    viewCount: '258550',
    likes: '9157',
    playLink: 'http://www.youtube.com/embed/l6qSgPOpJm4',
  },
  {
    platform: 'youtube',
    favorite: false,
    date: '2022-09-25T22:01:50.297Z',
    videoId: 'nMVOpdI_nWg',
    title: 'Dziwni ludzie na konferencjach',
    img: 'https://i.ytimg.com/vi/nMVOpdI_nWg/mqdefault.jpg',
    viewCount: '444154',
    likes: '12884',
    playLink: 'http://www.youtube.com/embed/nMVOpdI_nWg',
  },
  {
    platform: 'youtube',
    favorite: false,
    date: '2022-09-25T22:02:03.136Z',
    videoId: '9riFf_Ex8bA',
    title: 'Co sądzisz o inflacji - zaskakująca sonda w Jeleniej Górze',
    img: 'https://i.ytimg.com/vi/9riFf_Ex8bA/mqdefault.jpg',
    viewCount: '301047',
    likes: '9854',
    playLink: 'http://www.youtube.com/embed/9riFf_Ex8bA',
  },
  {
    platform: 'youtube',
    favorite: false,
    date: '2022-09-25T22:02:14.386Z',
    videoId: 'wXOXpZCGXDs',
    title: 'Gdy zaprosisz kumpli od komputerów by podkręcili ci sprzęt',
    img: 'https://i.ytimg.com/vi/wXOXpZCGXDs/mqdefault.jpg',
    viewCount: '222903',
    likes: '7889',
    playLink: 'http://www.youtube.com/embed/wXOXpZCGXDs',
  },
  {
    platform: 'youtube',
    favorite: false,
    date: '2022-09-25T22:02:25.394Z',
    videoId: 'b-gQusyIHGU',
    title: 'Jak zostać coachem',
    img: 'https://i.ytimg.com/vi/b-gQusyIHGU/mqdefault.jpg',
    viewCount: '354414',
    likes: '11263',
    playLink: 'http://www.youtube.com/embed/b-gQusyIHGU',
  },
  {
    platform: 'youtube',
    favorite: false,
    date: '2022-09-25T22:02:41.088Z',
    videoId: 'e4n15OGWzEk',
    title: 'Okulista online',
    img: 'https://i.ytimg.com/vi/e4n15OGWzEk/mqdefault.jpg',
    viewCount: '262956',
    likes: '8514',
    playLink: 'http://www.youtube.com/embed/e4n15OGWzEk',
  },
  {
    platform: 'youtube',
    favorite: false,
    date: '2022-09-25T22:02:55.836Z',
    videoId: 's8960bze69s',
    title: 'Gdy przed zakupem robisz doktorat w internecie',
    img: 'https://i.ytimg.com/vi/s8960bze69s/mqdefault.jpg',
    viewCount: '333202',
    likes: '12678',
    playLink: 'http://www.youtube.com/embed/s8960bze69s',
  },
  {
    platform: 'youtube',
    favorite: false,
    date: '2022-09-25T22:04:01.902Z',
    videoId: 'nZWP5D-fwQ4',
    title: 'Pomóżcie nam uratować życie dziecka kolegi z CodeTwo',
    img: 'https://i.ytimg.com/vi/nZWP5D-fwQ4/mqdefault.jpg',
    viewCount: '224681',
    likes: '14189',
    playLink: 'http://www.youtube.com/embed/nZWP5D-fwQ4',
  },
  {
    platform: 'youtube',
    favorite: false,
    date: '2022-09-25T22:04:11.919Z',
    videoId: 'MaY-gzD_PWE',
    title: 'Mega-konferencje po pandemii - tego jeszcze nie było',
    img: 'https://i.ytimg.com/vi/MaY-gzD_PWE/mqdefault.jpg',
    viewCount: '236392',
    likes: '6943',
    playLink: 'http://www.youtube.com/embed/MaY-gzD_PWE',
  },
  {
    platform: 'youtube',
    favorite: false,
    date: '2022-09-25T22:04:23.360Z',
    videoId: 'VywYYelE4lw',
    title: 'Uważajcie na fałszywe zbiórki dla uchodźców z Ukrainy i na złodziei na OLX',
    img: 'https://i.ytimg.com/vi/VywYYelE4lw/mqdefault.jpg',
    viewCount: '134133',
    likes: '5866',
    playLink: 'http://www.youtube.com/embed/VywYYelE4lw',
  },
  {
    platform: 'youtube',
    favorite: false,
    date: '2022-09-25T22:04:31.627Z',
    videoId: 'EI_pm5cpdFI',
    title: 'Ataki cybernetyczne - zabezpiecz swoje dane, pilnuj swoich pieniędzy',
    img: 'https://i.ytimg.com/vi/EI_pm5cpdFI/mqdefault.jpg',
    viewCount: '345710',
    likes: '15201',
    playLink: 'http://www.youtube.com/embed/EI_pm5cpdFI',
  },
  {
    platform: 'youtube',
    favorite: false,
    date: '2022-09-25T22:04:39.857Z',
    videoId: 'sRp31aK19IY',
    title: 'Cebulinium - pierwsza kryptowaluta dająca 100% gwarancji zysku',
    img: 'https://i.ytimg.com/vi/sRp31aK19IY/mqdefault.jpg',
    viewCount: '366113',
    likes: '10353',
    playLink: 'http://www.youtube.com/embed/sRp31aK19IY',
  },
  {
    platform: 'youtube',
    favorite: false,
    date: '2022-09-25T22:04:54.752Z',
    videoId: 'WUeq2Lv4aS8',
    title: 'Gdy dzwonisz do szefa powiedzieć, że dostałeś L4',
    img: 'https://i.ytimg.com/vi/WUeq2Lv4aS8/mqdefault.jpg',
    viewCount: '817613',
    likes: '16491',
    playLink: 'http://www.youtube.com/embed/WUeq2Lv4aS8',
  },
];
