export enum Content {
  title = 'Video-App',
  tooltipDeleteAll = 'Usuń wszystko',
  tooltipGridChange = 'Zmień widok',
  tooltipLoved = 'Pokaż ulubione',
  tooltipSort = 'Sortuj',
  questionDefault = 'Czy na pewno?',
  questionDeleteAll = 'Czy na pewno chcesz usunąć wszystkie filmy?',
  addButton = 'Dodaj',
  plusSign = '+',
  inputLabel = 'Tutaj wklej link do filmu',
  close = 'Zamknij',
  yes = 'Tak',
  no = 'Nie',
}
